### ISSUE TITLE
`install.libs` script not working for "aarch64"

### ISSUE THREAD

**Issue by netique** [R-macos/R-mac-web#1]
Hi, I try to build R 4.2.0 for MacOS M1 ARM. I've successfully installed gfortran but many libraries are still missing. The script pointed out at https://mac.r-project.org/bin/ seemed to me like it would do the job, but the arch which I have is stated as unsupported. Is the script out-of-date or am I missing something?

``` r
R.version$arch
#> [1] "aarch64"
```

<sup>Created on 2022-03-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

This is OT, but it would be really nice to provide some complete and concise info on building R from source for M1 platforms. There are many guides and help pages around r-project.org but it is hard for me to follow them. https://github.com/R-macos/recipes seems like the thing but didn't work for me.

**Comment by s-u** [comment]
Ah, good catch, `R.version` reports the `autoconf` architecture, not the one reported by `uname -m` which is the more commonly used one, now fixed.

**Comment by s-u** [comment]
Yes, I agree that it would be nice to have a better guide. Also the `install.libs` way doesn't know about virtual packages like `r-base-dev`, because they don't actually create any artifacts, but it would be useful to include them in `PACKAGES` so that `install.libs` could simply use it instead of having to specify individual libraries.
